# Generated by Django 5.2.1 on 2025-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_beckresultado_delete_resultadobeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
